name: Build/Test checks
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  check_linux_build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install make gcc
      - uses: actions/checkout@v4
      - run: make
        env:
          DEBUG: 0
          ASAN: 0
          ANALYZER: 0
          LTO: 1
          NATIVE: 0

  check_linux_test:
    runs-on: ubuntu-latest
    needs: check_linux_build
    steps:
      - run: sudo apt install make gcc libcriterion-dev
      - uses: actions/checkout@v4
      - run: make tests_run
        env:
          DEBUG: 1
          ASAN: 1
          ANALYZER: 1
          LTO: 0
          NATIVE: 0
